### ISSUE TITLE
Remind me which lane numbers are which...

### ISSUE THREAD

**Issue by ben-chaney** [adus/portal-documentation#2]
Howdy!  I forgot how the lane numbers (as shown in the detector data as "lane number") map onto the real world.  Could you remind me about that somewhere in the documentation, thank you!  I do see that there's both a lanenumber and a agency_lane field in the detector metadata, but still not sure how to read them.

I'll take another look at the other documentation pages just in case. 

Thanks team!

~Ben Chaney @ ODOT Region 1

**Comment by kristinann** [comment]
I believe that in portal terms, lane 1 is the fast (left) lane. 

lanenumber matches the (old) ATMS numbering scheme. agency_lane is the lane number provided by the agency (the DAC for ODOT) and matches the maintenance folks usage of lane numbering.

Does that help?

**Comment by ben-chaney** [comment]
Yep!

Thanks,
~ Ben

**Comment by JustinSheets85** [comment]
I believe for Washington, this is the opposite. We use Lane 1 as the rightmost lane.

**Comment by kristinann** [comment]
Thanks @JustinSheets85. For the record, ODOT used to number lanes both ways internally - one division had 1 as leftmost and another and 1 as rightmost. PORTAL used 1 as leftmost because of the ODOT division we interacted with at the time.  I wonder if we should switch to using 1 as rightmost consistently.

Also note that I believe the database keeps track of "lane number" and "agency lane number"

**Comment by ben-chaney** [comment]
Thanks folks, I appreciate the help.  I'm closing the issue now.
