### ISSUE TITLE
Statem Basemap Needs Updating

### ISSUE THREAD

**Issue by CDeLeon94** [adus/portal-documentation#24]
https://portal.its.pdx.edu/tc

Map shows random tiles saying 
> These basemap tiles will no longer be available as of October 31, 2023
![image](https://github.com/adus/portal-documentation/assets/18326238/8ecf19e1-9f7e-48d1-855b-7a9c06f23862)

**Comment by basemelazzabi** [comment]
@CDeLeon94,  thank you for reporting this. We switched the mapping tiles a few weeks ago to use OSM tiles through out the Portal website, but this one seems to have slipped through the cracks. It should be fixed now. 

FYI: We are decommissioning the Arterial Signals page because our stakeholders don't seem to be interested in it. If you find this page useful in some way, please let us know how you are using it and how it helps you so that we can pass that along to our stakeholders and maybe we can reignite the interest.

Thanks again!
