### ISSUE TITLE
Clarification: Volume (VPLPH) vs. Average Volume in Station Two Quantity Charts

### ISSUE THREAD

**Issue by ben-chaney** [adus/portal-documentation#7]
Hello, 

Could you please clarify for me the difference between the "Volume (VPLPH)" and the "Average Volume" in the Station Two Quantity Charts?  When the charts are plotted, the "Average Volume" value is labeled as "Average Daily Volume," even when the resolution is less than a day, which is a bit confusing.

It seems like the profiles for the two match fairly closely, but are not quite identical.  I had originally thought that "Volume (VPLPH)" was an average value per lane, and "Average Volume" was the segment volume (all lanes).  However, two observations have led me to think that's not true: sometimes the "Volume (VPLPH)" is higher than the "Average Volume", and if I select a single lane the two values are not identical.

Thank you for your assistance, I appreciate the help.

~Ben

**Comment by kristinann** [comment]
@ben-chaney The two metrics were developed due to requests from planners at RTC. They wanted an average daily volume. I believe that you may see a difference if you look at daily numbers and not hourly. As I recall, the short story is that the VPLPH metric does not help planners who want to know ADT (average daily traffic).

@leetam can you look at the web site and check and see if what I'm recalling above matches what is displaying on the web site?

@basemelazzabi Could you find the code snippets that do these calculations so we can verify?

**Comment by basemelazzabi** [comment]
@kristinann, The code and the calculation used for AVG volume is [here](https://github.com/adus/portal/blob/9e23a626656daa55a40dff63e71beb18f65a5c11/application/libraries/Portalsql.php#L249) and for VPLH is in the same file line 256 (`case VOLUME`).

**Comment by ben-chaney** [comment]
Hi @kristinann ,

Thank you for the clarification.  This makes perfect sense now, thinking of the usefulness at the day or month scale.  I'm just not used to using it at that scale, my bad.  

It is a bit confusing that the values don't line up as I might expect at the hourly scale, but I'd bet there's a good explanation in the code that @basemelazzabi linked to...

**Comment by kristinann** [comment]
@ben-chaney And I think we could definitely have been more clear about what the different metrics meant.

I am off for spring break, if @leetam or @basemelazzabi can investigate this before I get back, please do, if not we'll dig in in April.
